Include Load Data from Ops in Influx Events
creditkarma/good-influx pull request #10
Opened 2017-05-24 14:42 UTC by AlecHFerguson

Previously, some of the data from `ops` events was not being included in the stats sent to InfluxDB.  In this pull request, we have included all `ops` data.

As discussed in #4 , we decided to separate out `ops` data into several events.  In this PR, a single `ops` event from Hapi Good will now emit:
* The same `ops` event as before (so backwards compatibility should not be broken)
* One of each of the following events for each port:
  * `ops_requests`
  * `ops_concurrents`
  * `ops_responseTimes`
* One `ops_sockets` event

We also improved unit test coverage quite a bit, with all formatters having explicit tests.

We have been using this module in production for a number of our services and it seems to be working quite nicely.  I have Grafana graphs that query most of the ops events.  We don't use this module to report other event types just yet, so if there is some way to beta test that out it might be nice.

Special thanks to @wei-hai-ck since he actually did the bulk of the work here -- but didn't want the glory of the pull request.

2017-05-24 14:44 UTC, AlecHFerguson commented on lib/formatters.js
> +    if (Number.isInteger(Number(value))) {
@sfabriece I tried to maintain the fix you added to Int, from `line-protocol.js`.  Please review.

2017-05-24 14:47 UTC, AlecHFerguson commented on lib/line-protocol.js
> -            query         : Qs.stringify(internals.String(event.query)),
@fhemberger Is this order of operations correct?  Format as string first, then pass to `Qs.stringify`?  When we unit tested we found that it didn't format correctly.  We reversed the order (see below) and it seemed to format nicely.

2017-05-24 14:49 UTC, AlecHFerguson commented on package.json
> +    "test": "lab -m 5000 -t 92 -v -La code",
We improved code coverage quite a bit.  Should we setup CI on this project?  I would be happy to try to wire in TravisCI or something to run on pull request creation, and to block merge if tests fail, have linting issues, have low code coverage, etc.

2017-05-24 14:52 UTC, AlecHFerguson commented on test/index.test.js
> + * TODO: Find some way to make sure this has actually been hit
Any ideas here?

2017-05-25 01:05 UTC, sfabriece commented on lib/formatters.js
> +    if (Number.isInteger(Number(value))) {
LGTM

2017-05-25 04:51 UTC, fhemberger commented on package.json
> +    "test": "lab -m 5000 -t 92 -v -La code",
@AlecHFerguson Yes, TravisCI support would be cool.

2017-05-25 05:32 UTC, fhemberger commented on lib/line-protocol.js
> -            query         : Qs.stringify(internals.String(event.query)),
@AlecHFerguson You're right. Should be the other way round.

2017-05-28 18:53 UTC, AlecHFerguson commented
How do these changes look overall?  Do we think these changes would improve the module?  Is the code clean, well tested, and easy to understand?  Any improvements I can make to the implementation?

My company has been using this version in several of our Node services in production, and it works really well for us.  Would be awesome to share it with the community if folks think it would be useful.  Several of my colleagues are familiar with Hapi Good so I can ask for some help in reviewing if it would be helpful.

2017-05-28 19:27 UTC, sfabriece commented
@fhemberger when will this PR be merged, there some nice things in here.

2017-05-28 19:49 UTC, AlecHFerguson commented
Thanks @sfabriece !  If you have some time to review the changes that would be awesome since you're pretty familiar with this module.

2017-05-29 06:45 UTC, fhemberger requested changes
Two little changes, otherwise LGTM.

2017-05-29 06:45 UTC, fhemberger commented on lib/line-protocol.js
>   * https://docs.influxdata.com/influxdb/v0.12/write_protocols/line/
Updated link: https://docs.influxdata.com/influxdb/v1.2//write_protocols/line_protocol_tutorial/

2017-05-29 06:45 UTC, fhemberger commented on lib/good-influx-udp.js
> +        if (isNaN(config.threshold) || config.threshold > 5) {
Please mirror the comment from the README here:
// Limit threshold for UDP protocol to avoid transmission errors

2017-05-29 13:48 UTC, AlecHFerguson commented on lib/good-influx-udp.js
> +        if (isNaN(config.threshold) || config.threshold > 5) {
Good call, will do.

2017-06-02 17:29 UTC, fhemberger commented
@AlecHFerguson Can you please resolve the conflicts? Otherwise I think it's good to merge. :+1:

2017-06-03 19:53 UTC, AlecHFerguson commented
@fhemberger The conflicts turned out to be quite thorny so I went ahead and created a new PR.  See #12.  Closing this one.

2017-06-03 19:53 UTC, closed without merging