Include Load Data from Ops in Influx Events Take II
creditkarma/good-influx pull request #12
Opened 2017-06-03 19:51 UTC by AlecHFerguson

_#10 became pretty thorny due to merge conflicts, so I decided to just create a new PR.  Description from that PR:_

Previously, some of the data from `ops` events was not being included in the stats sent to InfluxDB.  In this pull request, we have included all `ops` data.

As discussed in #4 , we decided to separate out `ops` data into several events.  In this PR, a single `ops` event from Hapi Good will now emit:
* The same `ops` event as before (so backwards compatibility should not be broken)
* One of each of the following events for each port:
  * `ops_requests`
  * `ops_concurrents`
  * `ops_responseTimes`
* One `ops_sockets` event

We also improved unit test coverage quite a bit, with all formatters having explicit tests.

We have been using this module in production for a number of our services and it seems to be working quite nicely.  I have Grafana graphs that query most of the ops events.  We don't use this module to report other event types just yet, so if there is some way to beta test that out it might be nice.

Special thanks to @wei-hai since he actually did the bulk of the work here -- but didn't want the glory of the pull request.

2017-06-06 15:25 UTC, fhemberger requested changes
LGTM.

2017-06-06 15:25 UTC, fhemberger commented on lib/good-influx-udp.js
> +        if (isNaN(config.threshold) || config.threshold > 5) {
`// Limit threshold for UDP protocol to avoid transmission errors`

2017-06-06 21:59 UTC, AlecHFerguson commented on lib/good-influx-udp.js
> +        if (isNaN(config.threshold) || config.threshold > 5) {
Oops!  Not sure how that got lost in the shuffle.  Will reinstate when I get home in a few hours.

2017-06-07 11:14 UTC, merged

2017-06-07 11:57 UTC, fhemberger commented
Just published `good-influx@2.3.0`, thank you @AlecHFerguson! :tada: